config/routes.rb
Rails.application.routes.draw do
 
  root 'cities#index'
  resources :cities do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :content, presence: true
    
    validates :content, length: { in: 2..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
      @cities = City.all
   
  end

  def destroy
    @city.destroy
    redirect_to cities_path, notice: "You have deleted the content!"
  end

  def confirm
    @city = City.new(blog_params)
    render :new if @city.invalid?
  end

  def new
    if params[:back]
      @city = City.new(blog_params)
    else
      @city = City.new
    end
  end

  def create
    @city = City.create(blog_params)
    if @city.save
      redirect_to cities_path, notice: "You have created new content!"
    else
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @city.update(blog_params)
      redirect_to cities_path, notice: "You have edited this content！"
    else
      render :edit
    end
  end

  private
  def blog_params
    params.require(:city).permit( :content)
  end
  def set_blog
    @city = City.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
    def choose_new_or_edit
     
        if action_name == 'new' || action_name == 'confirm'
              
            confirm_cities_path
           
        elsif action_name == 'edit'
            
            city_path
            
        end
    end
       
end

app/views/cities/_form.html.erb
<%= form_with(model: @city, local: true,url: choose_new_or_edit) do |form| %>
  

    <% if @city.errors.any? %>
      <div id="error_explanation">
        <h2><%= @city.errors.count %>errors occurred.</h2>
        <ul>
  
        <% @city.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="city_title">
      <%= form.label :State_the_city_with_Infos %>
      <%= form.text_field :content %>
    </div>
      <%= form.submit %>
      <%= link_to "Return to List of city screen", cities_path %>
    <% end %>
    <footer class="footer">
       <p class="foot-content"> <i>Designed by Blaise Gustave Under Dive Into Code Program</i></p>
   </footer>

app/views/cities/confirm.html.erb
<div class="header">
  CityApp
</div>
<h3>Send it with the following contents.</h3>

<%= form_with(model: @city, local: true, url: cities_path) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :content %>
  <p>content:<%= @city.content %></p>
  <%= form.submit  "submit" %>
<% end %>

<%= form_with(model: @city, url: new_city_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :content %>
  <%= form.submit "back" %>
<% end %>

<footer class="footer">
  <p class="foot-content"> <i>Designed by Blaise Gustave Under Dive Into Code Program</i></p>
</footer>

app/views/cities/edit.html.erb
<div class="header"></div>
<h2>Create a new blog</h2>

<%= render 'form' %>

app/views/cities/index.html.erb
<div class="header">
CityApp
</div>
<h1>List of Rwandan cities with Infos</h1>

<p><%= notice %></p>
<table>
  <tr>
    <th>Contents</th>
  </tr>

<% @cities.each do |blog| %>
  <tr>
  <tr>
    <td><%= blog.content %></td>
    <td><%= link_to link_to 'Check the details', city_path(blog.id) %></td>
    <td><%= link_to link_to "Edit this Content", edit_city_path(blog.id) %></td>
    <!-- Define here! -->
    <td><%= link_to link_to 'Delete this Content', city_path(blog.id), method: :delete %></td>
  </tr>
  </tr>
<% end %>

</table>

<br>

<%= link_to 'Post a new blog', new_city_path %>
<footer class="footer">
       <p class="foot-content"> <i>Designed by Blaise Gustave Under Dive Into Code Program</i></p>
   </footer>

app/views/cities/new.html.erb
<div class="header">
CityApp
</div>
<h2>Create a new blog</h2>

<%= render 'form' %>

app/views/cities/show.html.erb
<div class="header">
CityApp
</div>
<h1>Cities Detail Screen </h1>
<p>Title: <%= @city.name %></p>
<p>Contents: <%= @city.content %></p>
<footer class="footer">
  <p class="foot-content"> <i>Designed by Blaise Gustave Under Dive Into Code Program</i></p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetchrone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>